### ISSUE TITLE
Forwarded request appears to come from internal IP my dns server listens on rather than that of the curvedns forwarder or the actual source

### ISSUE THREAD

**Issue by fsantiago07044** [curvedns/curvedns#3]
My slave NS' see notifies (at least; makes me think possibly all requests) from the curvedns forwarder IP address rather than the actual​ source (the master NS; or any querying device). Curvedns is on the same boxes as my NS servers are, but different IP's. Can this be corrected?

**Comment by fsantiago07044** [comment]
clarification;

curvedns is assigned to IP A.

pdns listens on IP B.

when my master NS sends out a notify, the pdns logs of a slave reports the notifies coming from IP B (itself). This ip B is not the SOA record nor is it listed as an NS anymore. 

this is the product of me deploying curvedns. what am i doing wrong?

**Comment by hvt** [comment]
This is by design. CurveDNS will always be the source IP when contacting the authoritative nameserver. Why? Because in this way, CurveDNS is able to cryptobox the response.

What you might do is put the CurveDNS IP on some kind of whitelist, so that your pdns instance accepts notifications from it.
